/*
 * This file is part of the Nepomuk KDE project.
 *
 * This library is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation; either version 2 of the License, or
 * (at your option) any later version.
 * See the file "COPYING" for the exact licensing terms.
 */

/*
 * This file has been generated by the Nepomuk Resource class generator.
 * DO NOT EDIT THIS FILE.
 * ANY CHANGES WILL BE LOST.
 */

#include <nepomuk2/variant.h>
#include <nepomuk2/resourcemanager.h>
#include "archiveitem.h"



#include <QtCore/QDateTime>
#include <QtCore/QDate>
#include <QtCore/QTime>


Nepomuk2::ArchiveItem::ArchiveItem()
  : EmbeddedFileDataObject( QUrl(), QUrl::fromEncoded("http://www.semanticdesktop.org/ontologies/2007/03/22/nfo#ArchiveItem") )
{
}



Nepomuk2::ArchiveItem::ArchiveItem( const ArchiveItem& res )
  : EmbeddedFileDataObject( res )
{
}


Nepomuk2::ArchiveItem::ArchiveItem( const Nepomuk2::Resource& res )
  : EmbeddedFileDataObject( res )
{
}


Nepomuk2::ArchiveItem::ArchiveItem( const QString& uri )
  : EmbeddedFileDataObject( uri, QUrl::fromEncoded("http://www.semanticdesktop.org/ontologies/2007/03/22/nfo#ArchiveItem") )
{
}

Nepomuk2::ArchiveItem::ArchiveItem( const QUrl& uri )
  : EmbeddedFileDataObject( uri, QUrl::fromEncoded("http://www.semanticdesktop.org/ontologies/2007/03/22/nfo#ArchiveItem") )
{
}

Nepomuk2::ArchiveItem::ArchiveItem( const QString& uri, const QUrl& type )
  : EmbeddedFileDataObject( uri, type )
{
}


Nepomuk2::ArchiveItem::ArchiveItem( const QUrl& uri, const QUrl& type )
  : EmbeddedFileDataObject( uri, type )
{
}

Nepomuk2::ArchiveItem::~ArchiveItem()
{
}

Nepomuk2::ArchiveItem& Nepomuk2::ArchiveItem::operator=( const ArchiveItem& res )
{
    Resource::operator=( res );
    return *this;
}

QString Nepomuk2::ArchiveItem::resourceTypeUri()
{
    return QLatin1String("http://www.semanticdesktop.org/ontologies/2007/03/22/nfo#ArchiveItem");
}

QList<bool> Nepomuk2::ArchiveItem::isPasswordProtecteds() const
{
    return ( property( QUrl::fromEncoded("http://www.semanticdesktop.org/ontologies/2007/03/22/nfo#isPasswordProtected") ).toBoolList());
}

void Nepomuk2::ArchiveItem::setIsPasswordProtecteds( const QList<bool>& value )
{
    setProperty( QUrl::fromEncoded("http://www.semanticdesktop.org/ontologies/2007/03/22/nfo#isPasswordProtected"), Variant( value ) );
}

void Nepomuk2::ArchiveItem::addIsPasswordProtected( const bool& value )
{
    Variant v = property( QUrl::fromEncoded("http://www.semanticdesktop.org/ontologies/2007/03/22/nfo#isPasswordProtected") );
    v.append( value );
    setProperty( QUrl::fromEncoded("http://www.semanticdesktop.org/ontologies/2007/03/22/nfo#isPasswordProtected"), v );
}

bool Nepomuk2::ArchiveItem::isPasswordProtected() const
{
    return ( property( QUrl::fromEncoded("http://www.semanticdesktop.org/ontologies/2007/03/22/nfo#isPasswordProtected") ).toBoolList() << false ).first();
}

void Nepomuk2::ArchiveItem::setIsPasswordProtected( const bool& value )
{
    setProperty( QUrl::fromEncoded("http://www.semanticdesktop.org/ontologies/2007/03/22/nfo#isPasswordProtected"), Variant( value ) );
}

QUrl Nepomuk2::ArchiveItem::isPasswordProtectedUri()
{
    return QUrl::fromEncoded("http://www.semanticdesktop.org/ontologies/2007/03/22/nfo#isPasswordProtected");
}


