/*
 * This file is part of the Nepomuk KDE project.
 *
 * This library is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation; either version 2 of the License, or
 * (at your option) any later version.
 * See the file "COPYING" for the exact licensing terms.
 */

/*
 * This file has been generated by the Nepomuk Resource class generator.
 * DO NOT EDIT THIS FILE.
 * ANY CHANGES WILL BE LOST.
 */

#include <nepomuk2/variant.h>
#include <nepomuk2/resourcemanager.h>
#include "deletedresource.h"



#include <QtCore/QDateTime>
#include <QtCore/QDate>
#include <QtCore/QTime>


Nepomuk2::DeletedResource::DeletedResource()
  : FileDataObject( QUrl(), QUrl::fromEncoded("http://www.semanticdesktop.org/ontologies/2007/03/22/nfo#DeletedResource") )
{
}



Nepomuk2::DeletedResource::DeletedResource( const DeletedResource& res )
  : FileDataObject( res )
{
}


Nepomuk2::DeletedResource::DeletedResource( const Nepomuk2::Resource& res )
  : FileDataObject( res )
{
}


Nepomuk2::DeletedResource::DeletedResource( const QString& uri )
  : FileDataObject( uri, QUrl::fromEncoded("http://www.semanticdesktop.org/ontologies/2007/03/22/nfo#DeletedResource") )
{
}

Nepomuk2::DeletedResource::DeletedResource( const QUrl& uri )
  : FileDataObject( uri, QUrl::fromEncoded("http://www.semanticdesktop.org/ontologies/2007/03/22/nfo#DeletedResource") )
{
}

Nepomuk2::DeletedResource::DeletedResource( const QString& uri, const QUrl& type )
  : FileDataObject( uri, type )
{
}


Nepomuk2::DeletedResource::DeletedResource( const QUrl& uri, const QUrl& type )
  : FileDataObject( uri, type )
{
}

Nepomuk2::DeletedResource::~DeletedResource()
{
}

Nepomuk2::DeletedResource& Nepomuk2::DeletedResource::operator=( const DeletedResource& res )
{
    Resource::operator=( res );
    return *this;
}

QString Nepomuk2::DeletedResource::resourceTypeUri()
{
    return QLatin1String("http://www.semanticdesktop.org/ontologies/2007/03/22/nfo#DeletedResource");
}

QList<QDateTime> Nepomuk2::DeletedResource::deletionDates() const
{
    return ( property( QUrl::fromEncoded("http://www.semanticdesktop.org/ontologies/2007/03/22/nfo#deletionDate") ).toDateTimeList());
}

void Nepomuk2::DeletedResource::setDeletionDates( const QList<QDateTime>& value )
{
    setProperty( QUrl::fromEncoded("http://www.semanticdesktop.org/ontologies/2007/03/22/nfo#deletionDate"), Variant( value ) );
}

void Nepomuk2::DeletedResource::addDeletionDate( const QDateTime& value )
{
    Variant v = property( QUrl::fromEncoded("http://www.semanticdesktop.org/ontologies/2007/03/22/nfo#deletionDate") );
    v.append( value );
    setProperty( QUrl::fromEncoded("http://www.semanticdesktop.org/ontologies/2007/03/22/nfo#deletionDate"), v );
}

QDateTime Nepomuk2::DeletedResource::deletionDate() const
{
    return ( property( QUrl::fromEncoded("http://www.semanticdesktop.org/ontologies/2007/03/22/nfo#deletionDate") ).toDateTimeList() << QDateTime() ).first();
}

void Nepomuk2::DeletedResource::setDeletionDate( const QDateTime& value )
{
    setProperty( QUrl::fromEncoded("http://www.semanticdesktop.org/ontologies/2007/03/22/nfo#deletionDate"), Variant( value ) );
}

QUrl Nepomuk2::DeletedResource::deletionDateUri()
{
    return QUrl::fromEncoded("http://www.semanticdesktop.org/ontologies/2007/03/22/nfo#deletionDate");
}

QStringList Nepomuk2::DeletedResource::originalLocations() const
{
    return ( property( QUrl::fromEncoded("http://www.semanticdesktop.org/ontologies/2007/03/22/nfo#originalLocation") ).toStringList());
}

void Nepomuk2::DeletedResource::setOriginalLocations( const QStringList& value )
{
    setProperty( QUrl::fromEncoded("http://www.semanticdesktop.org/ontologies/2007/03/22/nfo#originalLocation"), Variant( value ) );
}

void Nepomuk2::DeletedResource::addOriginalLocation( const QString& value )
{
    Variant v = property( QUrl::fromEncoded("http://www.semanticdesktop.org/ontologies/2007/03/22/nfo#originalLocation") );
    v.append( value );
    setProperty( QUrl::fromEncoded("http://www.semanticdesktop.org/ontologies/2007/03/22/nfo#originalLocation"), v );
}

QString Nepomuk2::DeletedResource::originalLocation() const
{
    return ( property( QUrl::fromEncoded("http://www.semanticdesktop.org/ontologies/2007/03/22/nfo#originalLocation") ).toStringList() << QString() ).first();
}

void Nepomuk2::DeletedResource::setOriginalLocation( const QString& value )
{
    setProperty( QUrl::fromEncoded("http://www.semanticdesktop.org/ontologies/2007/03/22/nfo#originalLocation"), Variant( value ) );
}

QUrl Nepomuk2::DeletedResource::originalLocationUri()
{
    return QUrl::fromEncoded("http://www.semanticdesktop.org/ontologies/2007/03/22/nfo#originalLocation");
}


