/*
 * This file is part of the Nepomuk KDE project.
 *
 * This library is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation; either version 2 of the License, or
 * (at your option) any later version.
 * See the file "COPYING" for the exact licensing terms.
 */

/*
 * This file has been generated by the Nepomuk Resource class generator.
 * DO NOT EDIT THIS FILE.
 * ANY CHANGES WILL BE LOST.
 */

#include <nepomuk2/variant.h>
#include <nepomuk2/resourcemanager.h>
#include "filehash.h"

#include "filedataobject.h"

#include <QtCore/QDateTime>
#include <QtCore/QDate>
#include <QtCore/QTime>


Nepomuk2::FileHash::FileHash()
  : Resource( QUrl(), QUrl::fromEncoded("http://www.semanticdesktop.org/ontologies/2007/03/22/nfo#FileHash") )
{
}



Nepomuk2::FileHash::FileHash( const FileHash& res )
  : Resource( res )
{
}


Nepomuk2::FileHash::FileHash( const Nepomuk2::Resource& res )
  : Resource( res )
{
}


Nepomuk2::FileHash::FileHash( const QString& uri )
  : Resource( uri, QUrl::fromEncoded("http://www.semanticdesktop.org/ontologies/2007/03/22/nfo#FileHash") )
{
}

Nepomuk2::FileHash::FileHash( const QUrl& uri )
  : Resource( uri, QUrl::fromEncoded("http://www.semanticdesktop.org/ontologies/2007/03/22/nfo#FileHash") )
{
}

Nepomuk2::FileHash::FileHash( const QString& uri, const QUrl& type )
  : Resource( uri, type )
{
}


Nepomuk2::FileHash::FileHash( const QUrl& uri, const QUrl& type )
  : Resource( uri, type )
{
}

Nepomuk2::FileHash::~FileHash()
{
}

Nepomuk2::FileHash& Nepomuk2::FileHash::operator=( const FileHash& res )
{
    Resource::operator=( res );
    return *this;
}

QString Nepomuk2::FileHash::resourceTypeUri()
{
    return QLatin1String("http://www.semanticdesktop.org/ontologies/2007/03/22/nfo#FileHash");
}

QStringList Nepomuk2::FileHash::hAlgorithms() const
{
    return ( property( QUrl::fromEncoded("http://www.semanticdesktop.org/ontologies/2007/03/22/nfo#hashAlgorithm") ).toStringList());
}

void Nepomuk2::FileHash::setHAlgorithms( const QStringList& value )
{
    setProperty( QUrl::fromEncoded("http://www.semanticdesktop.org/ontologies/2007/03/22/nfo#hashAlgorithm"), Variant( value ) );
}

void Nepomuk2::FileHash::addHAlgorithm( const QString& value )
{
    Variant v = property( QUrl::fromEncoded("http://www.semanticdesktop.org/ontologies/2007/03/22/nfo#hashAlgorithm") );
    v.append( value );
    setProperty( QUrl::fromEncoded("http://www.semanticdesktop.org/ontologies/2007/03/22/nfo#hashAlgorithm"), v );
}

QString Nepomuk2::FileHash::hAlgorithm() const
{
    return ( property( QUrl::fromEncoded("http://www.semanticdesktop.org/ontologies/2007/03/22/nfo#hashAlgorithm") ).toStringList() << QString() ).first();
}

void Nepomuk2::FileHash::setHAlgorithm( const QString& value )
{
    setProperty( QUrl::fromEncoded("http://www.semanticdesktop.org/ontologies/2007/03/22/nfo#hashAlgorithm"), Variant( value ) );
}

QUrl Nepomuk2::FileHash::hAlgorithmUri()
{
    return QUrl::fromEncoded("http://www.semanticdesktop.org/ontologies/2007/03/22/nfo#hashAlgorithm");
}

QStringList Nepomuk2::FileHash::hValues() const
{
    return ( property( QUrl::fromEncoded("http://www.semanticdesktop.org/ontologies/2007/03/22/nfo#hashValue") ).toStringList());
}

void Nepomuk2::FileHash::setHValues( const QStringList& value )
{
    setProperty( QUrl::fromEncoded("http://www.semanticdesktop.org/ontologies/2007/03/22/nfo#hashValue"), Variant( value ) );
}

void Nepomuk2::FileHash::addHValue( const QString& value )
{
    Variant v = property( QUrl::fromEncoded("http://www.semanticdesktop.org/ontologies/2007/03/22/nfo#hashValue") );
    v.append( value );
    setProperty( QUrl::fromEncoded("http://www.semanticdesktop.org/ontologies/2007/03/22/nfo#hashValue"), v );
}

QString Nepomuk2::FileHash::hValue() const
{
    return ( property( QUrl::fromEncoded("http://www.semanticdesktop.org/ontologies/2007/03/22/nfo#hashValue") ).toStringList() << QString() ).first();
}

void Nepomuk2::FileHash::setHValue( const QString& value )
{
    setProperty( QUrl::fromEncoded("http://www.semanticdesktop.org/ontologies/2007/03/22/nfo#hashValue"), Variant( value ) );
}

QUrl Nepomuk2::FileHash::hValueUri()
{
    return QUrl::fromEncoded("http://www.semanticdesktop.org/ontologies/2007/03/22/nfo#hashValue");
}


