/*
 * This file is part of the Nepomuk KDE project.
 *
 * This library is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation; either version 2 of the License, or
 * (at your option) any later version.
 * See the file "COPYING" for the exact licensing terms.
 */

/*
 * This file has been generated by the Nepomuk Resource class generator.
 * DO NOT EDIT THIS FILE.
 * ANY CHANGES WILL BE LOST.
 */

#include <nepomuk2/variant.h>
#include <nepomuk2/resourcemanager.h>
#include "htmldocument.h"



#include <QtCore/QDateTime>
#include <QtCore/QDate>
#include <QtCore/QTime>


Nepomuk2::HtmlDocument::HtmlDocument()
  : PlainTextDocument( QUrl(), QUrl::fromEncoded("http://www.semanticdesktop.org/ontologies/2007/03/22/nfo#HtmlDocument") )
{
}



Nepomuk2::HtmlDocument::HtmlDocument( const HtmlDocument& res )
  : PlainTextDocument( res )
{
}


Nepomuk2::HtmlDocument::HtmlDocument( const Nepomuk2::Resource& res )
  : PlainTextDocument( res )
{
}


Nepomuk2::HtmlDocument::HtmlDocument( const QString& uri )
  : PlainTextDocument( uri, QUrl::fromEncoded("http://www.semanticdesktop.org/ontologies/2007/03/22/nfo#HtmlDocument") )
{
}

Nepomuk2::HtmlDocument::HtmlDocument( const QUrl& uri )
  : PlainTextDocument( uri, QUrl::fromEncoded("http://www.semanticdesktop.org/ontologies/2007/03/22/nfo#HtmlDocument") )
{
}

Nepomuk2::HtmlDocument::HtmlDocument( const QString& uri, const QUrl& type )
  : PlainTextDocument( uri, type )
{
}


Nepomuk2::HtmlDocument::HtmlDocument( const QUrl& uri, const QUrl& type )
  : PlainTextDocument( uri, type )
{
}

Nepomuk2::HtmlDocument::~HtmlDocument()
{
}

Nepomuk2::HtmlDocument& Nepomuk2::HtmlDocument::operator=( const HtmlDocument& res )
{
    Resource::operator=( res );
    return *this;
}

QString Nepomuk2::HtmlDocument::resourceTypeUri()
{
    return QLatin1String("http://www.semanticdesktop.org/ontologies/2007/03/22/nfo#HtmlDocument");
}


