/*
 * This file is part of the Nepomuk KDE project.
 *
 * This library is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation; either version 2 of the License, or
 * (at your option) any later version.
 * See the file "COPYING" for the exact licensing terms.
 */

/*
 * This file has been generated by the Nepomuk Resource class generator.
 * DO NOT EDIT THIS FILE.
 * ANY CHANGES WILL BE LOST.
 */

#include <nepomuk2/variant.h>
#include <nepomuk2/resourcemanager.h>
#include "icon.h"



#include <QtCore/QDateTime>
#include <QtCore/QDate>
#include <QtCore/QTime>


Nepomuk2::Icon::Icon()
  : Image( QUrl(), QUrl::fromEncoded("http://www.semanticdesktop.org/ontologies/2007/03/22/nfo#Icon") )
{
}



Nepomuk2::Icon::Icon( const Icon& res )
  : Image( res )
{
}


Nepomuk2::Icon::Icon( const Nepomuk2::Resource& res )
  : Image( res )
{
}


Nepomuk2::Icon::Icon( const QString& uri )
  : Image( uri, QUrl::fromEncoded("http://www.semanticdesktop.org/ontologies/2007/03/22/nfo#Icon") )
{
}

Nepomuk2::Icon::Icon( const QUrl& uri )
  : Image( uri, QUrl::fromEncoded("http://www.semanticdesktop.org/ontologies/2007/03/22/nfo#Icon") )
{
}

Nepomuk2::Icon::Icon( const QString& uri, const QUrl& type )
  : Image( uri, type )
{
}


Nepomuk2::Icon::Icon( const QUrl& uri, const QUrl& type )
  : Image( uri, type )
{
}

Nepomuk2::Icon::~Icon()
{
}

Nepomuk2::Icon& Nepomuk2::Icon::operator=( const Icon& res )
{
    Resource::operator=( res );
    return *this;
}

QString Nepomuk2::Icon::resourceTypeUri()
{
    return QLatin1String("http://www.semanticdesktop.org/ontologies/2007/03/22/nfo#Icon");
}


