/*
 * This file is part of the Nepomuk KDE project.
 *
 * This library is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation; either version 2 of the License, or
 * (at your option) any later version.
 * See the file "COPYING" for the exact licensing terms.
 */

/*
 * This file has been generated by the Nepomuk Resource class generator.
 * DO NOT EDIT THIS FILE.
 * ANY CHANGES WILL BE LOST.
 */

#include <nepomuk2/variant.h>
#include <nepomuk2/resourcemanager.h>
#include "operatingsystem.h"



#include <QtCore/QDateTime>
#include <QtCore/QDate>
#include <QtCore/QTime>


Nepomuk2::OperatingSystem::OperatingSystem()
  : Software( QUrl(), QUrl::fromEncoded("http://www.semanticdesktop.org/ontologies/2007/03/22/nfo#OperatingSystem") )
{
}



Nepomuk2::OperatingSystem::OperatingSystem( const OperatingSystem& res )
  : Software( res )
{
}


Nepomuk2::OperatingSystem::OperatingSystem( const Nepomuk2::Resource& res )
  : Software( res )
{
}


Nepomuk2::OperatingSystem::OperatingSystem( const QString& uri )
  : Software( uri, QUrl::fromEncoded("http://www.semanticdesktop.org/ontologies/2007/03/22/nfo#OperatingSystem") )
{
}

Nepomuk2::OperatingSystem::OperatingSystem( const QUrl& uri )
  : Software( uri, QUrl::fromEncoded("http://www.semanticdesktop.org/ontologies/2007/03/22/nfo#OperatingSystem") )
{
}

Nepomuk2::OperatingSystem::OperatingSystem( const QString& uri, const QUrl& type )
  : Software( uri, type )
{
}


Nepomuk2::OperatingSystem::OperatingSystem( const QUrl& uri, const QUrl& type )
  : Software( uri, type )
{
}

Nepomuk2::OperatingSystem::~OperatingSystem()
{
}

Nepomuk2::OperatingSystem& Nepomuk2::OperatingSystem::operator=( const OperatingSystem& res )
{
    Resource::operator=( res );
    return *this;
}

QString Nepomuk2::OperatingSystem::resourceTypeUri()
{
    return QLatin1String("http://www.semanticdesktop.org/ontologies/2007/03/22/nfo#OperatingSystem");
}


