/*
 * This file is part of the Nepomuk KDE project.
 *
 * This library is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation; either version 2 of the License, or
 * (at your option) any later version.
 * See the file "COPYING" for the exact licensing terms.
 */

/*
 * This file has been generated by the Nepomuk Resource class generator.
 * DO NOT EDIT THIS FILE.
 * ANY CHANGES WILL BE LOST.
 */

#include <nepomuk2/variant.h>
#include <nepomuk2/resourcemanager.h>
#include "plaintextdocument.h"



#include <QtCore/QDateTime>
#include <QtCore/QDate>
#include <QtCore/QTime>


Nepomuk2::PlainTextDocument::PlainTextDocument()
  : TextDocument( QUrl(), QUrl::fromEncoded("http://www.semanticdesktop.org/ontologies/2007/03/22/nfo#PlainTextDocument") )
{
}



Nepomuk2::PlainTextDocument::PlainTextDocument( const PlainTextDocument& res )
  : TextDocument( res )
{
}


Nepomuk2::PlainTextDocument::PlainTextDocument( const Nepomuk2::Resource& res )
  : TextDocument( res )
{
}


Nepomuk2::PlainTextDocument::PlainTextDocument( const QString& uri )
  : TextDocument( uri, QUrl::fromEncoded("http://www.semanticdesktop.org/ontologies/2007/03/22/nfo#PlainTextDocument") )
{
}

Nepomuk2::PlainTextDocument::PlainTextDocument( const QUrl& uri )
  : TextDocument( uri, QUrl::fromEncoded("http://www.semanticdesktop.org/ontologies/2007/03/22/nfo#PlainTextDocument") )
{
}

Nepomuk2::PlainTextDocument::PlainTextDocument( const QString& uri, const QUrl& type )
  : TextDocument( uri, type )
{
}


Nepomuk2::PlainTextDocument::PlainTextDocument( const QUrl& uri, const QUrl& type )
  : TextDocument( uri, type )
{
}

Nepomuk2::PlainTextDocument::~PlainTextDocument()
{
}

Nepomuk2::PlainTextDocument& Nepomuk2::PlainTextDocument::operator=( const PlainTextDocument& res )
{
    Resource::operator=( res );
    return *this;
}

QString Nepomuk2::PlainTextDocument::resourceTypeUri()
{
    return QLatin1String("http://www.semanticdesktop.org/ontologies/2007/03/22/nfo#PlainTextDocument");
}


