/*
 * This file is part of the Nepomuk KDE project.
 *
 * This library is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation; either version 2 of the License, or
 * (at your option) any later version.
 * See the file "COPYING" for the exact licensing terms.
 */

/*
 * This file has been generated by the Nepomuk Resource class generator.
 * DO NOT EDIT THIS FILE.
 * ANY CHANGES WILL BE LOST.
 */

#include <nepomuk2/variant.h>
#include <nepomuk2/resourcemanager.h>
#include "spreadsheet.h"



#include <QtCore/QDateTime>
#include <QtCore/QDate>
#include <QtCore/QTime>


Nepomuk2::Spreadsheet::Spreadsheet()
  : Document( QUrl(), QUrl::fromEncoded("http://www.semanticdesktop.org/ontologies/2007/03/22/nfo#Spreadsheet") )
{
}



Nepomuk2::Spreadsheet::Spreadsheet( const Spreadsheet& res )
  : Document( res )
{
}


Nepomuk2::Spreadsheet::Spreadsheet( const Nepomuk2::Resource& res )
  : Document( res )
{
}


Nepomuk2::Spreadsheet::Spreadsheet( const QString& uri )
  : Document( uri, QUrl::fromEncoded("http://www.semanticdesktop.org/ontologies/2007/03/22/nfo#Spreadsheet") )
{
}

Nepomuk2::Spreadsheet::Spreadsheet( const QUrl& uri )
  : Document( uri, QUrl::fromEncoded("http://www.semanticdesktop.org/ontologies/2007/03/22/nfo#Spreadsheet") )
{
}

Nepomuk2::Spreadsheet::Spreadsheet( const QString& uri, const QUrl& type )
  : Document( uri, type )
{
}


Nepomuk2::Spreadsheet::Spreadsheet( const QUrl& uri, const QUrl& type )
  : Document( uri, type )
{
}

Nepomuk2::Spreadsheet::~Spreadsheet()
{
}

Nepomuk2::Spreadsheet& Nepomuk2::Spreadsheet::operator=( const Spreadsheet& res )
{
    Resource::operator=( res );
    return *this;
}

QString Nepomuk2::Spreadsheet::resourceTypeUri()
{
    return QLatin1String("http://www.semanticdesktop.org/ontologies/2007/03/22/nfo#Spreadsheet");
}


