/*
 * This file is part of the Nepomuk KDE project.
 *
 * This library is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation; either version 2 of the License, or
 * (at your option) any later version.
 * See the file "COPYING" for the exact licensing terms.
 */

/*
 * This file has been generated by the Nepomuk Resource class generator.
 * DO NOT EDIT THIS FILE.
 * ANY CHANGES WILL BE LOST.
 */

#ifndef _TAG_H_
#define _TAG_H_

class QDateTime;
class QDate;
class QTime;

namespace Nepomuk2 {
    class Resource;

}

#include "resource.h"


namespace Nepomuk2 {

    /**
     * Represents a generic tag 
     */
    class  Tag : public Resource
    {
    public:
        /**
         * Create a new empty and invalid Tag instance
         */
        Tag();

        /**
         * Default copy constructor
         */
        Tag( const Tag& );
        Tag( const Resource& );

        /**
         * Create a new Tag instance representing the resource
         * referenced by \a uriOrIdentifier.
         */
        Tag( const QString& uriOrIdentifier );

        /**
         * Create a new Tag instance representing the resource
         * referenced by \a uri.
         */
        Tag( const QUrl& uri );
        ~Tag();

        Tag& operator=( const Tag& );

        /**
         * Get property 'isTagFor'. States which resources a tag is associated 
         * with 
         */
        QList<Resource> isTagFors() const;

        /**
         * Set property 'isTagFor'. States which resources a tag is associated 
         * with 
         */
        void setIsTagFors( const QList<Resource>& value );

        /**
         * Add a value to property 'isTagFor'. States which resources 
         * a tag is associated with 
         */
        void addIsTagFor( const Resource& value );

        /**
         * \return The URI of the property 'isTagFor'. 
         */
        static QUrl isTagForUri();

        /**
         * Retrieve a list of all available Tag resources. This list consists 
         * of all resource of type Tag that are stored in the local Nepomuk 
         * meta data storage and any changes made locally. Be aware that 
         * in some cases this list can get very big. Then it might be better 
         * to use libKNep directly. 
         */
        static QList<Tag> allTags();


        /**
         * \return The URI of the resource type that is used in Tag instances.
         */
        static QString resourceTypeUri();

    protected:
       Tag( const QString& uri, const QUrl& type );
       Tag( const QUrl& uri, const QUrl& type );
    };
}

#endif
