/*
 * This file is part of the Nepomuk KDE project.
 *
 * This library is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation; either version 2 of the License, or
 * (at your option) any later version.
 * See the file "COPYING" for the exact licensing terms.
 */

/*
 * This file has been generated by the Nepomuk Resource class generator.
 * DO NOT EDIT THIS FILE.
 * ANY CHANGES WILL BE LOST.
 */

#include <nepomuk2/variant.h>
#include <nepomuk2/resourcemanager.h>
#include "bill.h"



#include <QtCore/QDateTime>
#include <QtCore/QDate>
#include <QtCore/QTime>


Nepomuk2::Bill::Bill()
  : Legislation( QUrl(), QUrl::fromEncoded("http://www.example.com/nbib#Bill") )
{
}



Nepomuk2::Bill::Bill( const Bill& res )
  : Legislation( res )
{
}


Nepomuk2::Bill::Bill( const Nepomuk2::Resource& res )
  : Legislation( res )
{
}


Nepomuk2::Bill::Bill( const QString& uri )
  : Legislation( uri, QUrl::fromEncoded("http://www.example.com/nbib#Bill") )
{
}

Nepomuk2::Bill::Bill( const QUrl& uri )
  : Legislation( uri, QUrl::fromEncoded("http://www.example.com/nbib#Bill") )
{
}

Nepomuk2::Bill::Bill( const QString& uri, const QUrl& type )
  : Legislation( uri, type )
{
}


Nepomuk2::Bill::Bill( const QUrl& uri, const QUrl& type )
  : Legislation( uri, type )
{
}

Nepomuk2::Bill::~Bill()
{
}

Nepomuk2::Bill& Nepomuk2::Bill::operator=( const Bill& res )
{
    Resource::operator=( res );
    return *this;
}

QString Nepomuk2::Bill::resourceTypeUri()
{
    return QLatin1String("http://www.example.com/nbib#Bill");
}


