/*
 * This file is part of the Nepomuk KDE project.
 *
 * This library is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation; either version 2 of the License, or
 * (at your option) any later version.
 * See the file "COPYING" for the exact licensing terms.
 */

/*
 * This file has been generated by the Nepomuk Resource class generator.
 * DO NOT EDIT THIS FILE.
 * ANY CHANGES WILL BE LOST.
 */

#ifndef _BLOG_H_
#define _BLOG_H_

class QDateTime;
class QDate;
class QTime;

namespace Nepomuk2 {

}

#include "collection.h"


namespace Nepomuk2 {

    /**
     * Reference the blog in which several BlogPost can be found 
     */
    class  Blog : public Collection
    {
    public:
        /**
         * Create a new empty and invalid Blog instance
         */
        Blog();

        /**
         * Default copy constructor
         */
        Blog( const Blog& );
        Blog( const Resource& );

        /**
         * Create a new Blog instance representing the resource
         * referenced by \a uriOrIdentifier.
         */
        Blog( const QString& uriOrIdentifier );

        /**
         * Create a new Blog instance representing the resource
         * referenced by \a uri.
         */
        Blog( const QUrl& uri );
        ~Blog();

        Blog& operator=( const Blog& );

        /**
         * Retrieve a list of all available Blog resources. This list consists 
         * of all resource of type Blog that are stored in the local Nepomuk 
         * meta data storage and any changes made locally. Be aware that 
         * in some cases this list can get very big. Then it might be better 
         * to use libKNep directly. 
         */
        static QList<Blog> allBlogs();


        /**
         * \return The URI of the resource type that is used in Blog instances.
         */
        static QString resourceTypeUri();

    protected:
       Blog( const QString& uri, const QUrl& type );
       Blog( const QUrl& uri, const QUrl& type );
    };
}

#endif
