/*
 * This file is part of the Nepomuk KDE project.
 *
 * This library is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation; either version 2 of the License, or
 * (at your option) any later version.
 * See the file "COPYING" for the exact licensing terms.
 */

/*
 * This file has been generated by the Nepomuk Resource class generator.
 * DO NOT EDIT THIS FILE.
 * ANY CHANGES WILL BE LOST.
 */

#ifndef _BOOK_H_
#define _BOOK_H_

class QDateTime;
class QDate;
class QTime;

namespace Nepomuk2 {

}

#include "publication.h"


namespace Nepomuk2 {

    /**
     * A book with an explicit publisher. 
     */
    class  Book : public Publication
    {
    public:
        /**
         * Create a new empty and invalid Book instance
         */
        Book();

        /**
         * Default copy constructor
         */
        Book( const Book& );
        Book( const Resource& );

        /**
         * Create a new Book instance representing the resource
         * referenced by \a uriOrIdentifier.
         */
        Book( const QString& uriOrIdentifier );

        /**
         * Create a new Book instance representing the resource
         * referenced by \a uri.
         */
        Book( const QUrl& uri );
        ~Book();

        Book& operator=( const Book& );

        /**
         * Retrieve a list of all available Book resources. This list consists 
         * of all resource of type Book that are stored in the local Nepomuk 
         * meta data storage and any changes made locally. Be aware that 
         * in some cases this list can get very big. Then it might be better 
         * to use libKNep directly. 
         */
        static QList<Book> allBooks();


        /**
         * \return The URI of the resource type that is used in Book instances.
         */
        static QString resourceTypeUri();

    protected:
       Book( const QString& uri, const QUrl& type );
       Book( const QUrl& uri, const QUrl& type );
    };
}

#endif
