/*
 * This file is part of the Nepomuk KDE project.
 *
 * This library is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation; either version 2 of the License, or
 * (at your option) any later version.
 * See the file "COPYING" for the exact licensing terms.
 */

/*
 * This file has been generated by the Nepomuk Resource class generator.
 * DO NOT EDIT THIS FILE.
 * ANY CHANGES WILL BE LOST.
 */

#include <nepomuk2/variant.h>
#include <nepomuk2/resourcemanager.h>
#include "encyclopedia.h"



#include <QtCore/QDateTime>
#include <QtCore/QDate>
#include <QtCore/QTime>


Nepomuk2::Encyclopedia::Encyclopedia()
  : Collection( QUrl(), QUrl::fromEncoded("http://www.example.com/nbib#Encyclopedia") )
{
}



Nepomuk2::Encyclopedia::Encyclopedia( const Encyclopedia& res )
  : Collection( res )
{
}


Nepomuk2::Encyclopedia::Encyclopedia( const Nepomuk2::Resource& res )
  : Collection( res )
{
}


Nepomuk2::Encyclopedia::Encyclopedia( const QString& uri )
  : Collection( uri, QUrl::fromEncoded("http://www.example.com/nbib#Encyclopedia") )
{
}

Nepomuk2::Encyclopedia::Encyclopedia( const QUrl& uri )
  : Collection( uri, QUrl::fromEncoded("http://www.example.com/nbib#Encyclopedia") )
{
}

Nepomuk2::Encyclopedia::Encyclopedia( const QString& uri, const QUrl& type )
  : Collection( uri, type )
{
}


Nepomuk2::Encyclopedia::Encyclopedia( const QUrl& uri, const QUrl& type )
  : Collection( uri, type )
{
}

Nepomuk2::Encyclopedia::~Encyclopedia()
{
}

Nepomuk2::Encyclopedia& Nepomuk2::Encyclopedia::operator=( const Encyclopedia& res )
{
    Resource::operator=( res );
    return *this;
}

QString Nepomuk2::Encyclopedia::resourceTypeUri()
{
    return QLatin1String("http://www.example.com/nbib#Encyclopedia");
}


