/*
 * This file is part of the Nepomuk KDE project.
 *
 * This library is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation; either version 2 of the License, or
 * (at your option) any later version.
 * See the file "COPYING" for the exact licensing terms.
 */

/*
 * This file has been generated by the Nepomuk Resource class generator.
 * DO NOT EDIT THIS FILE.
 * ANY CHANGES WILL BE LOST.
 */

#include <nepomuk2/variant.h>
#include <nepomuk2/resourcemanager.h>
#include "event.h"

#include "publication.h"

#include <QtCore/QDateTime>
#include <QtCore/QDate>
#include <QtCore/QTime>


Nepomuk2::Event::Event()
  : Resource( QUrl(), QUrl::fromEncoded("http://www.semanticdesktop.org/ontologies/2007/11/01/pimo#Event") )
{
}



Nepomuk2::Event::Event( const Event& res )
  : Resource( res )
{
}


Nepomuk2::Event::Event( const Nepomuk2::Resource& res )
  : Resource( res )
{
}


Nepomuk2::Event::Event( const QString& uri )
  : Resource( uri, QUrl::fromEncoded("http://www.semanticdesktop.org/ontologies/2007/11/01/pimo#Event") )
{
}

Nepomuk2::Event::Event( const QUrl& uri )
  : Resource( uri, QUrl::fromEncoded("http://www.semanticdesktop.org/ontologies/2007/11/01/pimo#Event") )
{
}

Nepomuk2::Event::Event( const QString& uri, const QUrl& type )
  : Resource( uri, type )
{
}


Nepomuk2::Event::Event( const QUrl& uri, const QUrl& type )
  : Resource( uri, type )
{
}

Nepomuk2::Event::~Event()
{
}

Nepomuk2::Event& Nepomuk2::Event::operator=( const Event& res )
{
    Resource::operator=( res );
    return *this;
}

QString Nepomuk2::Event::resourceTypeUri()
{
    return QLatin1String("http://www.semanticdesktop.org/ontologies/2007/11/01/pimo#Event");
}

QList<Nepomuk2::Publication> Nepomuk2::Event::eventPublications() const
{
    // We always store all Resource types as plain Resource objects.
    // It does not introduce any overhead (due to the implicit sharing of
    // the data and has the advantage that we can mix setProperty calls
    // with the special Resource subclass methods.
    // More importantly Resource loads the data as Resource objects anyway.
    QList<Publication> rl;
    QList<Resource> l = property( QUrl::fromEncoded("http://www.example.com/nbib#eventPublication") ).toResourceList() ;
    for( QList<Resource>::const_iterator it = l.constBegin();
        it != l.constEnd(); ++it )
    rl.append( Publication( *it ) );
    return rl;
}

void Nepomuk2::Event::setEventPublications( const QList<Nepomuk2::Publication>& value )
{
    // We always store all Resource types as plain Resource objects.
    // It does not introduce any overhead (due to the implicit sharing of
    // the data and has the advantage that we can mix setProperty calls
    // with the special Resource subclass methods.
    // More importantly Resource loads the data as Resource objects anyway.
    QList<Resource> l;
    for( QList<Publication>::const_iterator it = value.constBegin();
         it != value.constEnd(); ++it ) {
        l.append( Resource( (*it) ) );
    }
    setProperty( QUrl::fromEncoded("http://www.example.com/nbib#eventPublication"), Variant( l ) );
}

void Nepomuk2::Event::addEventPublication( const Nepomuk2::Publication& value )
{
    // We always store all Resource types as plain Resource objects.
    // It does not introduce any overhead (due to the implicit sharing of
    // the data and has the advantage that we can mix setProperty calls
    // with the special Resource subclass methods.
    // More importantly Resource loads the data as Resource objects anyway.
    Variant v = property( QUrl::fromEncoded("http://www.example.com/nbib#eventPublication") );
    v.append( Resource( value ) );
    setProperty( QUrl::fromEncoded("http://www.example.com/nbib#eventPublication"), v );
}

QUrl Nepomuk2::Event::eventPublicationUri()
{
    return QUrl::fromEncoded("http://www.example.com/nbib#eventPublication");
}


