/*
 * This file is part of the Nepomuk KDE project.
 *
 * This library is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation; either version 2 of the License, or
 * (at your option) any later version.
 * See the file "COPYING" for the exact licensing terms.
 */

/*
 * This file has been generated by the Nepomuk Resource class generator.
 * DO NOT EDIT THIS FILE.
 * ANY CHANGES WILL BE LOST.
 */

#ifndef _JOURNALISSUE_H_
#define _JOURNALISSUE_H_

class QDateTime;
class QDate;
class QTime;

namespace Nepomuk2 {

}

#include "collection.h"


namespace Nepomuk2 {

    /**
     * A journal issue for serious, scholarly publications 
     */
    class  JournalIssue : public Collection
    {
    public:
        /**
         * Create a new empty and invalid JournalIssue instance
         */
        JournalIssue();

        /**
         * Default copy constructor
         */
        JournalIssue( const JournalIssue& );
        JournalIssue( const Resource& );

        /**
         * Create a new JournalIssue instance representing the resource
         * referenced by \a uriOrIdentifier.
         */
        JournalIssue( const QString& uriOrIdentifier );

        /**
         * Create a new JournalIssue instance representing the resource
         * referenced by \a uri.
         */
        JournalIssue( const QUrl& uri );
        ~JournalIssue();

        JournalIssue& operator=( const JournalIssue& );

        /**
         * Retrieve a list of all available JournalIssue resources. This 
         * list consists of all resource of type JournalIssue that are 
         * stored in the local Nepomuk meta data storage and any changes 
         * made locally. Be aware that in some cases this list can get very 
         * big. Then it might be better to use libKNep directly. 
         */
        static QList<JournalIssue> allJournalIssues();


        /**
         * \return The URI of the resource type that is used in JournalIssue instances.
         */
        static QString resourceTypeUri();

    protected:
       JournalIssue( const QString& uri, const QUrl& type );
       JournalIssue( const QUrl& uri, const QUrl& type );
    };
}

#endif
