/*
 * This file is part of the Nepomuk KDE project.
 *
 * This library is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation; either version 2 of the License, or
 * (at your option) any later version.
 * See the file "COPYING" for the exact licensing terms.
 */

/*
 * This file has been generated by the Nepomuk Resource class generator.
 * DO NOT EDIT THIS FILE.
 * ANY CHANGES WILL BE LOST.
 */

#ifndef _MAGAZIN_H_
#define _MAGAZIN_H_

class QDateTime;
class QDate;
class QTime;

namespace Nepomuk2 {

}

#include "series.h"


namespace Nepomuk2 {

    /**
     * A Magazin which publish several MagazinIssue containing several 
     * articles 
     */
    class  Magazin : public Series
    {
    public:
        /**
         * Create a new empty and invalid Magazin instance
         */
        Magazin();

        /**
         * Default copy constructor
         */
        Magazin( const Magazin& );
        Magazin( const Resource& );

        /**
         * Create a new Magazin instance representing the resource
         * referenced by \a uriOrIdentifier.
         */
        Magazin( const QString& uriOrIdentifier );

        /**
         * Create a new Magazin instance representing the resource
         * referenced by \a uri.
         */
        Magazin( const QUrl& uri );
        ~Magazin();

        Magazin& operator=( const Magazin& );

        /**
         * Retrieve a list of all available Magazin resources. This list 
         * consists of all resource of type Magazin that are stored in the 
         * local Nepomuk meta data storage and any changes made locally. 
         * Be aware that in some cases this list can get very big. Then it 
         * might be better to use libKNep directly. 
         */
        static QList<Magazin> allMagazins();


        /**
         * \return The URI of the resource type that is used in Magazin instances.
         */
        static QString resourceTypeUri();

    protected:
       Magazin( const QString& uri, const QUrl& type );
       Magazin( const QUrl& uri, const QUrl& type );
    };
}

#endif
