/*
 * This file is part of the Nepomuk KDE project.
 *
 * This library is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation; either version 2 of the License, or
 * (at your option) any later version.
 * See the file "COPYING" for the exact licensing terms.
 */

/*
 * This file has been generated by the Nepomuk Resource class generator.
 * DO NOT EDIT THIS FILE.
 * ANY CHANGES WILL BE LOST.
 */

#include <nepomuk2/variant.h>
#include <nepomuk2/resourcemanager.h>
#include "reference.h"

#include "publication.h"
#include "documentpart.h"
#include "informationelement.h"

#include <QtCore/QDateTime>
#include <QtCore/QDate>
#include <QtCore/QTime>


Nepomuk2::Reference::Reference()
  : InformationElement( QUrl(), QUrl::fromEncoded("http://www.example.com/nbib#Reference") )
{
}



Nepomuk2::Reference::Reference( const Reference& res )
  : InformationElement( res )
{
}


Nepomuk2::Reference::Reference( const Nepomuk2::Resource& res )
  : InformationElement( res )
{
}


Nepomuk2::Reference::Reference( const QString& uri )
  : InformationElement( uri, QUrl::fromEncoded("http://www.example.com/nbib#Reference") )
{
}

Nepomuk2::Reference::Reference( const QUrl& uri )
  : InformationElement( uri, QUrl::fromEncoded("http://www.example.com/nbib#Reference") )
{
}

Nepomuk2::Reference::Reference( const QString& uri, const QUrl& type )
  : InformationElement( uri, type )
{
}


Nepomuk2::Reference::Reference( const QUrl& uri, const QUrl& type )
  : InformationElement( uri, type )
{
}

Nepomuk2::Reference::~Reference()
{
}

Nepomuk2::Reference& Nepomuk2::Reference::operator=( const Reference& res )
{
    Resource::operator=( res );
    return *this;
}

QString Nepomuk2::Reference::resourceTypeUri()
{
    return QLatin1String("http://www.example.com/nbib#Reference");
}

QStringList Nepomuk2::Reference::citeKeys() const
{
    return ( property( QUrl::fromEncoded("http://www.example.com/nbib#citeKey") ).toStringList());
}

void Nepomuk2::Reference::setCiteKeys( const QStringList& value )
{
    setProperty( QUrl::fromEncoded("http://www.example.com/nbib#citeKey"), Variant( value ) );
}

void Nepomuk2::Reference::addCiteKey( const QString& value )
{
    Variant v = property( QUrl::fromEncoded("http://www.example.com/nbib#citeKey") );
    v.append( value );
    setProperty( QUrl::fromEncoded("http://www.example.com/nbib#citeKey"), v );
}

QString Nepomuk2::Reference::citeKey() const
{
    return ( property( QUrl::fromEncoded("http://www.example.com/nbib#citeKey") ).toStringList() << QString() ).first();
}

void Nepomuk2::Reference::setCiteKey( const QString& value )
{
    setProperty( QUrl::fromEncoded("http://www.example.com/nbib#citeKey"), Variant( value ) );
}

QUrl Nepomuk2::Reference::citeKeyUri()
{
    return QUrl::fromEncoded("http://www.example.com/nbib#citeKey");
}

QList<Nepomuk2::DocumentPart> Nepomuk2::Reference::referencedParts() const
{
    // We always store all Resource types as plain Resource objects.
    // It does not introduce any overhead (due to the implicit sharing of
    // the data and has the advantage that we can mix setProperty calls
    // with the special Resource subclass methods.
    // More importantly Resource loads the data as Resource objects anyway.
    QList<DocumentPart> rl;
    QList<Resource> l = property( QUrl::fromEncoded("http://www.example.com/nbib#referencedPart") ).toResourceList() ;
    for( QList<Resource>::const_iterator it = l.constBegin();
        it != l.constEnd(); ++it )
    rl.append( DocumentPart( *it ) );
    return rl;
}

void Nepomuk2::Reference::setReferencedParts( const QList<Nepomuk2::DocumentPart>& value )
{
    // We always store all Resource types as plain Resource objects.
    // It does not introduce any overhead (due to the implicit sharing of
    // the data and has the advantage that we can mix setProperty calls
    // with the special Resource subclass methods.
    // More importantly Resource loads the data as Resource objects anyway.
    QList<Resource> l;
    for( QList<DocumentPart>::const_iterator it = value.constBegin();
         it != value.constEnd(); ++it ) {
        l.append( Resource( (*it) ) );
    }
    setProperty( QUrl::fromEncoded("http://www.example.com/nbib#referencedPart"), Variant( l ) );
}

void Nepomuk2::Reference::addReferencedPart( const Nepomuk2::DocumentPart& value )
{
    // We always store all Resource types as plain Resource objects.
    // It does not introduce any overhead (due to the implicit sharing of
    // the data and has the advantage that we can mix setProperty calls
    // with the special Resource subclass methods.
    // More importantly Resource loads the data as Resource objects anyway.
    Variant v = property( QUrl::fromEncoded("http://www.example.com/nbib#referencedPart") );
    v.append( Resource( value ) );
    setProperty( QUrl::fromEncoded("http://www.example.com/nbib#referencedPart"), v );
}

Nepomuk2::DocumentPart Nepomuk2::Reference::referencedPart() const
{
    // We always store all Resource types as plain Resource objects.
    // It does not introduce any overhead (due to the implicit sharing of
    // the data and has the advantage that we can mix setProperty calls
    // with the special Resource subclass methods.
    // More importantly Resource loads the data as Resource objects anyway.
    return DocumentPart( property( QUrl::fromEncoded("http://www.example.com/nbib#referencedPart") ).toResource().uri() );
}

void Nepomuk2::Reference::setReferencedPart( const Nepomuk2::DocumentPart& value )
{
    setProperty( QUrl::fromEncoded("http://www.example.com/nbib#referencedPart"), Variant( value ) );
}

QUrl Nepomuk2::Reference::referencedPartUri()
{
    return QUrl::fromEncoded("http://www.example.com/nbib#referencedPart");
}

QList<Nepomuk2::Publication> Nepomuk2::Reference::publications() const
{
    // We always store all Resource types as plain Resource objects.
    // It does not introduce any overhead (due to the implicit sharing of
    // the data and has the advantage that we can mix setProperty calls
    // with the special Resource subclass methods.
    // More importantly Resource loads the data as Resource objects anyway.
    QList<Publication> rl;
    QList<Resource> l = property( QUrl::fromEncoded("http://www.example.com/nbib#publication") ).toResourceList() ;
    for( QList<Resource>::const_iterator it = l.constBegin();
        it != l.constEnd(); ++it )
    rl.append( Publication( *it ) );
    return rl;
}

void Nepomuk2::Reference::setPublications( const QList<Nepomuk2::Publication>& value )
{
    // We always store all Resource types as plain Resource objects.
    // It does not introduce any overhead (due to the implicit sharing of
    // the data and has the advantage that we can mix setProperty calls
    // with the special Resource subclass methods.
    // More importantly Resource loads the data as Resource objects anyway.
    QList<Resource> l;
    for( QList<Publication>::const_iterator it = value.constBegin();
         it != value.constEnd(); ++it ) {
        l.append( Resource( (*it) ) );
    }
    setProperty( QUrl::fromEncoded("http://www.example.com/nbib#publication"), Variant( l ) );
}

void Nepomuk2::Reference::addPublication( const Nepomuk2::Publication& value )
{
    // We always store all Resource types as plain Resource objects.
    // It does not introduce any overhead (due to the implicit sharing of
    // the data and has the advantage that we can mix setProperty calls
    // with the special Resource subclass methods.
    // More importantly Resource loads the data as Resource objects anyway.
    Variant v = property( QUrl::fromEncoded("http://www.example.com/nbib#publication") );
    v.append( Resource( value ) );
    setProperty( QUrl::fromEncoded("http://www.example.com/nbib#publication"), v );
}

Nepomuk2::Publication Nepomuk2::Reference::publication() const
{
    // We always store all Resource types as plain Resource objects.
    // It does not introduce any overhead (due to the implicit sharing of
    // the data and has the advantage that we can mix setProperty calls
    // with the special Resource subclass methods.
    // More importantly Resource loads the data as Resource objects anyway.
    return Publication( property( QUrl::fromEncoded("http://www.example.com/nbib#publication") ).toResource().uri() );
}

void Nepomuk2::Reference::setPublication( const Nepomuk2::Publication& value )
{
    setProperty( QUrl::fromEncoded("http://www.example.com/nbib#publication"), Variant( value ) );
}

QUrl Nepomuk2::Reference::publicationUri()
{
    return QUrl::fromEncoded("http://www.example.com/nbib#publication");
}

QStringList Nepomuk2::Reference::pageses() const
{
    return ( property( QUrl::fromEncoded("http://www.example.com/nbib#pages") ).toStringList());
}

void Nepomuk2::Reference::setPageses( const QStringList& value )
{
    setProperty( QUrl::fromEncoded("http://www.example.com/nbib#pages"), Variant( value ) );
}

void Nepomuk2::Reference::addPages( const QString& value )
{
    Variant v = property( QUrl::fromEncoded("http://www.example.com/nbib#pages") );
    v.append( value );
    setProperty( QUrl::fromEncoded("http://www.example.com/nbib#pages"), v );
}

QString Nepomuk2::Reference::pages() const
{
    return ( property( QUrl::fromEncoded("http://www.example.com/nbib#pages") ).toStringList() << QString() ).first();
}

void Nepomuk2::Reference::setPages( const QString& value )
{
    setProperty( QUrl::fromEncoded("http://www.example.com/nbib#pages"), Variant( value ) );
}

QUrl Nepomuk2::Reference::pagesUri()
{
    return QUrl::fromEncoded("http://www.example.com/nbib#pages");
}


