/*
 * This file is part of the Nepomuk KDE project.
 *
 * This library is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation; either version 2 of the License, or
 * (at your option) any later version.
 * See the file "COPYING" for the exact licensing terms.
 */

/*
 * This file has been generated by the Nepomuk Resource class generator.
 * DO NOT EDIT THIS FILE.
 * ANY CHANGES WILL BE LOST.
 */

#include <nepomuk2/variant.h>
#include <nepomuk2/resourcemanager.h>
#include "statute.h"



#include <QtCore/QDateTime>
#include <QtCore/QDate>
#include <QtCore/QTime>


Nepomuk2::Statute::Statute()
  : Legislation( QUrl(), QUrl::fromEncoded("http://www.example.com/nbib#Statute") )
{
}



Nepomuk2::Statute::Statute( const Statute& res )
  : Legislation( res )
{
}


Nepomuk2::Statute::Statute( const Nepomuk2::Resource& res )
  : Legislation( res )
{
}


Nepomuk2::Statute::Statute( const QString& uri )
  : Legislation( uri, QUrl::fromEncoded("http://www.example.com/nbib#Statute") )
{
}

Nepomuk2::Statute::Statute( const QUrl& uri )
  : Legislation( uri, QUrl::fromEncoded("http://www.example.com/nbib#Statute") )
{
}

Nepomuk2::Statute::Statute( const QString& uri, const QUrl& type )
  : Legislation( uri, type )
{
}


Nepomuk2::Statute::Statute( const QUrl& uri, const QUrl& type )
  : Legislation( uri, type )
{
}

Nepomuk2::Statute::~Statute()
{
}

Nepomuk2::Statute& Nepomuk2::Statute::operator=( const Statute& res )
{
    Resource::operator=( res );
    return *this;
}

QString Nepomuk2::Statute::resourceTypeUri()
{
    return QLatin1String("http://www.example.com/nbib#Statute");
}

QStringList Nepomuk2::Statute::publicLawNumbers() const
{
    return ( property( QUrl::fromEncoded("http://www.example.com/nbib#publicLawNumber") ).toStringList());
}

void Nepomuk2::Statute::setPublicLawNumbers( const QStringList& value )
{
    setProperty( QUrl::fromEncoded("http://www.example.com/nbib#publicLawNumber"), Variant( value ) );
}

void Nepomuk2::Statute::addPublicLawNumber( const QString& value )
{
    Variant v = property( QUrl::fromEncoded("http://www.example.com/nbib#publicLawNumber") );
    v.append( value );
    setProperty( QUrl::fromEncoded("http://www.example.com/nbib#publicLawNumber"), v );
}

QUrl Nepomuk2::Statute::publicLawNumberUri()
{
    return QUrl::fromEncoded("http://www.example.com/nbib#publicLawNumber");
}


