/*
 * This file is part of the Nepomuk KDE project.
 *
 * This library is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation; either version 2 of the License, or
 * (at your option) any later version.
 * See the file "COPYING" for the exact licensing terms.
 */

/*
 * This file has been generated by the Nepomuk Resource class generator.
 * DO NOT EDIT THIS FILE.
 * ANY CHANGES WILL BE LOST.
 */

#include <nepomuk2/variant.h>
#include <nepomuk2/resourcemanager.h>
#include "blogpost.h"



#include <QtCore/QDateTime>
#include <QtCore/QDate>
#include <QtCore/QTime>


Nepomuk2::BlogPost::BlogPost()
  : Document( QUrl(), QUrl::fromEncoded("http://www.semanticdesktop.org/ontologies/2007/11/01/pimo#BlogPost") )
{
}



Nepomuk2::BlogPost::BlogPost( const BlogPost& res )
  : Document( res )
{
}


Nepomuk2::BlogPost::BlogPost( const Nepomuk2::Resource& res )
  : Document( res )
{
}


Nepomuk2::BlogPost::BlogPost( const QString& uri )
  : Document( uri, QUrl::fromEncoded("http://www.semanticdesktop.org/ontologies/2007/11/01/pimo#BlogPost") )
{
}

Nepomuk2::BlogPost::BlogPost( const QUrl& uri )
  : Document( uri, QUrl::fromEncoded("http://www.semanticdesktop.org/ontologies/2007/11/01/pimo#BlogPost") )
{
}

Nepomuk2::BlogPost::BlogPost( const QString& uri, const QUrl& type )
  : Document( uri, type )
{
}


Nepomuk2::BlogPost::BlogPost( const QUrl& uri, const QUrl& type )
  : Document( uri, type )
{
}

Nepomuk2::BlogPost::~BlogPost()
{
}

Nepomuk2::BlogPost& Nepomuk2::BlogPost::operator=( const BlogPost& res )
{
    Resource::operator=( res );
    return *this;
}

QString Nepomuk2::BlogPost::resourceTypeUri()
{
    return QLatin1String("http://www.semanticdesktop.org/ontologies/2007/11/01/pimo#BlogPost");
}


