/*
 * This file is part of the Nepomuk KDE project.
 *
 * This library is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation; either version 2 of the License, or
 * (at your option) any later version.
 * See the file "COPYING" for the exact licensing terms.
 */

/*
 * This file has been generated by the Nepomuk Resource class generator.
 * DO NOT EDIT THIS FILE.
 * ANY CHANGES WILL BE LOST.
 */

#include <nepomuk2/variant.h>
#include <nepomuk2/resourcemanager.h>
#include "meeting.h"



#include <QtCore/QDateTime>
#include <QtCore/QDate>
#include <QtCore/QTime>


Nepomuk2::Meeting::Meeting()
  : SocialEvent( QUrl(), QUrl::fromEncoded("http://www.semanticdesktop.org/ontologies/2007/11/01/pimo#Meeting") )
{
}



Nepomuk2::Meeting::Meeting( const Meeting& res )
  : SocialEvent( res )
{
}


Nepomuk2::Meeting::Meeting( const Nepomuk2::Resource& res )
  : SocialEvent( res )
{
}


Nepomuk2::Meeting::Meeting( const QString& uri )
  : SocialEvent( uri, QUrl::fromEncoded("http://www.semanticdesktop.org/ontologies/2007/11/01/pimo#Meeting") )
{
}

Nepomuk2::Meeting::Meeting( const QUrl& uri )
  : SocialEvent( uri, QUrl::fromEncoded("http://www.semanticdesktop.org/ontologies/2007/11/01/pimo#Meeting") )
{
}

Nepomuk2::Meeting::Meeting( const QString& uri, const QUrl& type )
  : SocialEvent( uri, type )
{
}


Nepomuk2::Meeting::Meeting( const QUrl& uri, const QUrl& type )
  : SocialEvent( uri, type )
{
}

Nepomuk2::Meeting::~Meeting()
{
}

Nepomuk2::Meeting& Nepomuk2::Meeting::operator=( const Meeting& res )
{
    Resource::operator=( res );
    return *this;
}

QString Nepomuk2::Meeting::resourceTypeUri()
{
    return QLatin1String("http://www.semanticdesktop.org/ontologies/2007/11/01/pimo#Meeting");
}


