/*
 * This file is part of the Nepomuk KDE project.
 *
 * This library is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation; either version 2 of the License, or
 * (at your option) any later version.
 * See the file "COPYING" for the exact licensing terms.
 */

/*
 * This file has been generated by the Nepomuk Resource class generator.
 * DO NOT EDIT THIS FILE.
 * ANY CHANGES WILL BE LOST.
 */

#include <nepomuk2/variant.h>
#include <nepomuk2/resourcemanager.h>
#include "persongroup.h"

#include "collection.h"
#include "agent.h"

#include <QtCore/QDateTime>
#include <QtCore/QDate>
#include <QtCore/QTime>


Nepomuk2::PersonGroup::PersonGroup()
  : Collection( QUrl(), QUrl::fromEncoded("http://www.semanticdesktop.org/ontologies/2007/11/01/pimo#PersonGroup") )
{
}



Nepomuk2::PersonGroup::PersonGroup( const PersonGroup& res )
  : Collection( res )
{
}


Nepomuk2::PersonGroup::PersonGroup( const Nepomuk2::Resource& res )
  : Collection( res )
{
}


Nepomuk2::PersonGroup::PersonGroup( const QString& uri )
  : Collection( uri, QUrl::fromEncoded("http://www.semanticdesktop.org/ontologies/2007/11/01/pimo#PersonGroup") )
{
}

Nepomuk2::PersonGroup::PersonGroup( const QUrl& uri )
  : Collection( uri, QUrl::fromEncoded("http://www.semanticdesktop.org/ontologies/2007/11/01/pimo#PersonGroup") )
{
}

Nepomuk2::PersonGroup::PersonGroup( const QString& uri, const QUrl& type )
  : Collection( uri, type )
{
}


Nepomuk2::PersonGroup::PersonGroup( const QUrl& uri, const QUrl& type )
  : Collection( uri, type )
{
}

Nepomuk2::PersonGroup::~PersonGroup()
{
}

Nepomuk2::PersonGroup& Nepomuk2::PersonGroup::operator=( const PersonGroup& res )
{
    Resource::operator=( res );
    return *this;
}

QString Nepomuk2::PersonGroup::resourceTypeUri()
{
    return QLatin1String("http://www.semanticdesktop.org/ontologies/2007/11/01/pimo#PersonGroup");
}

Nepomuk2::Agent Nepomuk2::PersonGroup::toAgent() const
{
    return Nepomuk2::Agent( *this );
}

Nepomuk2::Collection Nepomuk2::PersonGroup::toCollection() const
{
    return Nepomuk2::Collection( *this );
}


