/*
 * This file is part of the Nepomuk KDE project.
 *
 * This library is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation; either version 2 of the License, or
 * (at your option) any later version.
 * See the file "COPYING" for the exact licensing terms.
 */

/*
 * This file has been generated by the Nepomuk Resource class generator.
 * DO NOT EDIT THIS FILE.
 * ANY CHANGES WILL BE LOST.
 */

#include <nepomuk2/variant.h>
#include <nepomuk2/resourcemanager.h>
#include "personalinformationmodel.h"

#include "agent.h"
#include "classorthingorpropertyorassociation.h"
#include "topic.h"

#include <QtCore/QDateTime>
#include <QtCore/QDate>
#include <QtCore/QTime>


Nepomuk2::PersonalInformationModel::PersonalInformationModel()
  : Resource( QUrl(), QUrl::fromEncoded("http://www.semanticdesktop.org/ontologies/2007/11/01/pimo#PersonalInformationModel") )
{
}



Nepomuk2::PersonalInformationModel::PersonalInformationModel( const PersonalInformationModel& res )
  : Resource( res )
{
}


Nepomuk2::PersonalInformationModel::PersonalInformationModel( const Nepomuk2::Resource& res )
  : Resource( res )
{
}


Nepomuk2::PersonalInformationModel::PersonalInformationModel( const QString& uri )
  : Resource( uri, QUrl::fromEncoded("http://www.semanticdesktop.org/ontologies/2007/11/01/pimo#PersonalInformationModel") )
{
}

Nepomuk2::PersonalInformationModel::PersonalInformationModel( const QUrl& uri )
  : Resource( uri, QUrl::fromEncoded("http://www.semanticdesktop.org/ontologies/2007/11/01/pimo#PersonalInformationModel") )
{
}

Nepomuk2::PersonalInformationModel::PersonalInformationModel( const QString& uri, const QUrl& type )
  : Resource( uri, type )
{
}


Nepomuk2::PersonalInformationModel::PersonalInformationModel( const QUrl& uri, const QUrl& type )
  : Resource( uri, type )
{
}

Nepomuk2::PersonalInformationModel::~PersonalInformationModel()
{
}

Nepomuk2::PersonalInformationModel& Nepomuk2::PersonalInformationModel::operator=( const PersonalInformationModel& res )
{
    Resource::operator=( res );
    return *this;
}

QString Nepomuk2::PersonalInformationModel::resourceTypeUri()
{
    return QLatin1String("http://www.semanticdesktop.org/ontologies/2007/11/01/pimo#PersonalInformationModel");
}

QStringList Nepomuk2::PersonalInformationModel::globalNamespaces() const
{
    return ( property( QUrl::fromEncoded("http://www.semanticdesktop.org/ontologies/2007/11/01/pimo#hasGlobalNamespace") ).toStringList());
}

void Nepomuk2::PersonalInformationModel::setGlobalNamespaces( const QStringList& value )
{
    setProperty( QUrl::fromEncoded("http://www.semanticdesktop.org/ontologies/2007/11/01/pimo#hasGlobalNamespace"), Variant( value ) );
}

void Nepomuk2::PersonalInformationModel::addGlobalNamespace( const QString& value )
{
    Variant v = property( QUrl::fromEncoded("http://www.semanticdesktop.org/ontologies/2007/11/01/pimo#hasGlobalNamespace") );
    v.append( value );
    setProperty( QUrl::fromEncoded("http://www.semanticdesktop.org/ontologies/2007/11/01/pimo#hasGlobalNamespace"), v );
}

QUrl Nepomuk2::PersonalInformationModel::globalNamespaceUri()
{
    return QUrl::fromEncoded("http://www.semanticdesktop.org/ontologies/2007/11/01/pimo#hasGlobalNamespace");
}

QStringList Nepomuk2::PersonalInformationModel::localNamespaces() const
{
    return ( property( QUrl::fromEncoded("http://www.semanticdesktop.org/ontologies/2007/11/01/pimo#hasLocalNamespace") ).toStringList());
}

void Nepomuk2::PersonalInformationModel::setLocalNamespaces( const QStringList& value )
{
    setProperty( QUrl::fromEncoded("http://www.semanticdesktop.org/ontologies/2007/11/01/pimo#hasLocalNamespace"), Variant( value ) );
}

void Nepomuk2::PersonalInformationModel::addLocalNamespace( const QString& value )
{
    Variant v = property( QUrl::fromEncoded("http://www.semanticdesktop.org/ontologies/2007/11/01/pimo#hasLocalNamespace") );
    v.append( value );
    setProperty( QUrl::fromEncoded("http://www.semanticdesktop.org/ontologies/2007/11/01/pimo#hasLocalNamespace"), v );
}

QUrl Nepomuk2::PersonalInformationModel::localNamespaceUri()
{
    return QUrl::fromEncoded("http://www.semanticdesktop.org/ontologies/2007/11/01/pimo#hasLocalNamespace");
}

QList<Nepomuk2::Topic> Nepomuk2::PersonalInformationModel::rootTopics() const
{
    // We always store all Resource types as plain Resource objects.
    // It does not introduce any overhead (due to the implicit sharing of
    // the data and has the advantage that we can mix setProperty calls
    // with the special Resource subclass methods.
    // More importantly Resource loads the data as Resource objects anyway.
    QList<Topic> rl;
    QList<Resource> l = property( QUrl::fromEncoded("http://www.semanticdesktop.org/ontologies/2007/11/01/pimo#hasRootTopic") ).toResourceList() ;
    for( QList<Resource>::const_iterator it = l.constBegin();
        it != l.constEnd(); ++it )
    rl.append( Topic( *it ) );
    return rl;
}

void Nepomuk2::PersonalInformationModel::setRootTopics( const QList<Nepomuk2::Topic>& value )
{
    // We always store all Resource types as plain Resource objects.
    // It does not introduce any overhead (due to the implicit sharing of
    // the data and has the advantage that we can mix setProperty calls
    // with the special Resource subclass methods.
    // More importantly Resource loads the data as Resource objects anyway.
    QList<Resource> l;
    for( QList<Topic>::const_iterator it = value.constBegin();
         it != value.constEnd(); ++it ) {
        l.append( Resource( (*it) ) );
    }
    setProperty( QUrl::fromEncoded("http://www.semanticdesktop.org/ontologies/2007/11/01/pimo#hasRootTopic"), Variant( l ) );
}

void Nepomuk2::PersonalInformationModel::addRootTopic( const Nepomuk2::Topic& value )
{
    // We always store all Resource types as plain Resource objects.
    // It does not introduce any overhead (due to the implicit sharing of
    // the data and has the advantage that we can mix setProperty calls
    // with the special Resource subclass methods.
    // More importantly Resource loads the data as Resource objects anyway.
    Variant v = property( QUrl::fromEncoded("http://www.semanticdesktop.org/ontologies/2007/11/01/pimo#hasRootTopic") );
    v.append( Resource( value ) );
    setProperty( QUrl::fromEncoded("http://www.semanticdesktop.org/ontologies/2007/11/01/pimo#hasRootTopic"), v );
}

QUrl Nepomuk2::PersonalInformationModel::rootTopicUri()
{
    return QUrl::fromEncoded("http://www.semanticdesktop.org/ontologies/2007/11/01/pimo#hasRootTopic");
}

QList<Nepomuk2::Agent> Nepomuk2::PersonalInformationModel::creators() const
{
    // We always store all Resource types as plain Resource objects.
    // It does not introduce any overhead (due to the implicit sharing of
    // the data and has the advantage that we can mix setProperty calls
    // with the special Resource subclass methods.
    // More importantly Resource loads the data as Resource objects anyway.
    QList<Agent> rl;
    QList<Resource> l = property( QUrl::fromEncoded("http://www.semanticdesktop.org/ontologies/2007/11/01/pimo#creator") ).toResourceList() ;
    for( QList<Resource>::const_iterator it = l.constBegin();
        it != l.constEnd(); ++it )
    rl.append( Agent( *it ) );
    return rl;
}

void Nepomuk2::PersonalInformationModel::setCreators( const QList<Nepomuk2::Agent>& value )
{
    // We always store all Resource types as plain Resource objects.
    // It does not introduce any overhead (due to the implicit sharing of
    // the data and has the advantage that we can mix setProperty calls
    // with the special Resource subclass methods.
    // More importantly Resource loads the data as Resource objects anyway.
    QList<Resource> l;
    for( QList<Agent>::const_iterator it = value.constBegin();
         it != value.constEnd(); ++it ) {
        l.append( Resource( (*it) ) );
    }
    setProperty( QUrl::fromEncoded("http://www.semanticdesktop.org/ontologies/2007/11/01/pimo#creator"), Variant( l ) );
}

void Nepomuk2::PersonalInformationModel::addCreator( const Nepomuk2::Agent& value )
{
    // We always store all Resource types as plain Resource objects.
    // It does not introduce any overhead (due to the implicit sharing of
    // the data and has the advantage that we can mix setProperty calls
    // with the special Resource subclass methods.
    // More importantly Resource loads the data as Resource objects anyway.
    Variant v = property( QUrl::fromEncoded("http://www.semanticdesktop.org/ontologies/2007/11/01/pimo#creator") );
    v.append( Resource( value ) );
    setProperty( QUrl::fromEncoded("http://www.semanticdesktop.org/ontologies/2007/11/01/pimo#creator"), v );
}

Nepomuk2::Agent Nepomuk2::PersonalInformationModel::creator() const
{
    // We always store all Resource types as plain Resource objects.
    // It does not introduce any overhead (due to the implicit sharing of
    // the data and has the advantage that we can mix setProperty calls
    // with the special Resource subclass methods.
    // More importantly Resource loads the data as Resource objects anyway.
    return Agent( property( QUrl::fromEncoded("http://www.semanticdesktop.org/ontologies/2007/11/01/pimo#creator") ).toResource().uri() );
}

void Nepomuk2::PersonalInformationModel::setCreator( const Nepomuk2::Agent& value )
{
    setProperty( QUrl::fromEncoded("http://www.semanticdesktop.org/ontologies/2007/11/01/pimo#creator"), Variant( value ) );
}

QUrl Nepomuk2::PersonalInformationModel::creatorUri()
{
    return QUrl::fromEncoded("http://www.semanticdesktop.org/ontologies/2007/11/01/pimo#creator");
}


