/*
 * This file is part of the Nepomuk KDE project.
 *
 * This library is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation; either version 2 of the License, or
 * (at your option) any later version.
 * See the file "COPYING" for the exact licensing terms.
 */

/*
 * This file has been generated by the Nepomuk Resource class generator.
 * DO NOT EDIT THIS FILE.
 * ANY CHANGES WILL BE LOST.
 */

#ifndef _PROJECT_H_
#define _PROJECT_H_

class QDateTime;
class QDate;
class QTime;

namespace Nepomuk2 {

}

#include "processconcept.h"


namespace Nepomuk2 {

    /**
     * Any piece of work that is undertaken or attempted (Wordnet). 
     * An enterprise carefully planned to achieve a particular aim 
     * (Oxford Dictionary). 
     */
    class  Project : public ProcessConcept
    {
    public:
        /**
         * Create a new empty and invalid Project instance
         */
        Project();

        /**
         * Default copy constructor
         */
        Project( const Project& );
        Project( const Resource& );

        /**
         * Create a new Project instance representing the resource
         * referenced by \a uriOrIdentifier.
         */
        Project( const QString& uriOrIdentifier );

        /**
         * Create a new Project instance representing the resource
         * referenced by \a uri.
         */
        Project( const QUrl& uri );
        ~Project();

        Project& operator=( const Project& );

        /**
         * Retrieve a list of all available Project resources. This list 
         * consists of all resource of type Project that are stored in the 
         * local Nepomuk meta data storage and any changes made locally. 
         * Be aware that in some cases this list can get very big. Then it 
         * might be better to use libKNep directly. 
         */
        static QList<Project> allProjects();


        /**
         * \return The URI of the resource type that is used in Project instances.
         */
        static QString resourceTypeUri();

    protected:
       Project( const QString& uri, const QUrl& type );
       Project( const QUrl& uri, const QUrl& type );
    };
}

#endif
