


#ifndef NEPOMUKMETADATAEXTRACTOR_EXPORT_H
#define NEPOMUKMETADATAEXTRACTOR_EXPORT_H
 
// needed for KDE_EXPORT and KDE_IMPORT macros
#include <kdemacros.h>
 
#ifndef NEPOMUKMETADATAEXTRACTOR_EXPORT
# if defined(MAKE_NEPOMUKMETADATAEXTRACTOR_LIB)
   // We are building this library
#  define NEPOMUKMETADATAEXTRACTOR_EXPORT KDE_EXPORT
# else
   // We are using this library
#  define NEPOMUKMETADATAEXTRACTOR_EXPORT KDE_IMPORT
# endif
#endif
 
# ifndef NEPOMUKMETADATAEXTRACTOR_EXPORT_DEPRECATED
#  define NEPOMUKMETADATAEXTRACTOR_EXPORT_DEPRECATED KDE_DEPRECATED NEPOMUKMETADATAEXTRACTOR_EXPORT
# endif
 
#endif 
