/*
 * This file is part of the Nepomuk KDE project.
 *
 * This library is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation; either version 2 of the License, or
 * (at your option) any later version.
 * See the file "COPYING" for the exact licensing terms.
 */

/*
 * This file has been generated by the Nepomuk Resource class generator.
 * DO NOT EDIT THIS FILE.
 * ANY CHANGES WILL BE LOST.
 */

#include <nepomuk2/variant.h>
#include <nepomuk2/resourcemanager.h>
#include "audioimaccount.h"



#include <QtCore/QDateTime>
#include <QtCore/QDate>
#include <QtCore/QTime>


Nepomuk2::AudioIMAccount::AudioIMAccount()
  : IMAccount( QUrl(), QUrl::fromEncoded("http://www.semanticdesktop.org/ontologies/2007/03/22/nco#AudioIMAccount") )
{
}



Nepomuk2::AudioIMAccount::AudioIMAccount( const AudioIMAccount& res )
  : IMAccount( res )
{
}


Nepomuk2::AudioIMAccount::AudioIMAccount( const Nepomuk2::Resource& res )
  : IMAccount( res )
{
}


Nepomuk2::AudioIMAccount::AudioIMAccount( const QString& uri )
  : IMAccount( uri, QUrl::fromEncoded("http://www.semanticdesktop.org/ontologies/2007/03/22/nco#AudioIMAccount") )
{
}

Nepomuk2::AudioIMAccount::AudioIMAccount( const QUrl& uri )
  : IMAccount( uri, QUrl::fromEncoded("http://www.semanticdesktop.org/ontologies/2007/03/22/nco#AudioIMAccount") )
{
}

Nepomuk2::AudioIMAccount::AudioIMAccount( const QString& uri, const QUrl& type )
  : IMAccount( uri, type )
{
}


Nepomuk2::AudioIMAccount::AudioIMAccount( const QUrl& uri, const QUrl& type )
  : IMAccount( uri, type )
{
}

Nepomuk2::AudioIMAccount::~AudioIMAccount()
{
}

Nepomuk2::AudioIMAccount& Nepomuk2::AudioIMAccount::operator=( const AudioIMAccount& res )
{
    Resource::operator=( res );
    return *this;
}

QString Nepomuk2::AudioIMAccount::resourceTypeUri()
{
    return QLatin1String("http://www.semanticdesktop.org/ontologies/2007/03/22/nco#AudioIMAccount");
}


