/*
 * This file is part of the Nepomuk KDE project.
 *
 * This library is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation; either version 2 of the License, or
 * (at your option) any later version.
 * See the file "COPYING" for the exact licensing terms.
 */

/*
 * This file has been generated by the Nepomuk Resource class generator.
 * DO NOT EDIT THIS FILE.
 * ANY CHANGES WILL BE LOST.
 */

#include <nepomuk2/variant.h>
#include <nepomuk2/resourcemanager.h>
#include "contactgroup.h"

#include "contact.h"

#include <QtCore/QDateTime>
#include <QtCore/QDate>
#include <QtCore/QTime>


Nepomuk2::ContactGroup::ContactGroup()
  : InformationElement( QUrl(), QUrl::fromEncoded("http://www.semanticdesktop.org/ontologies/2007/03/22/nco#ContactGroup") )
{
}



Nepomuk2::ContactGroup::ContactGroup( const ContactGroup& res )
  : InformationElement( res )
{
}


Nepomuk2::ContactGroup::ContactGroup( const Nepomuk2::Resource& res )
  : InformationElement( res )
{
}


Nepomuk2::ContactGroup::ContactGroup( const QString& uri )
  : InformationElement( uri, QUrl::fromEncoded("http://www.semanticdesktop.org/ontologies/2007/03/22/nco#ContactGroup") )
{
}

Nepomuk2::ContactGroup::ContactGroup( const QUrl& uri )
  : InformationElement( uri, QUrl::fromEncoded("http://www.semanticdesktop.org/ontologies/2007/03/22/nco#ContactGroup") )
{
}

Nepomuk2::ContactGroup::ContactGroup( const QString& uri, const QUrl& type )
  : InformationElement( uri, type )
{
}


Nepomuk2::ContactGroup::ContactGroup( const QUrl& uri, const QUrl& type )
  : InformationElement( uri, type )
{
}

Nepomuk2::ContactGroup::~ContactGroup()
{
}

Nepomuk2::ContactGroup& Nepomuk2::ContactGroup::operator=( const ContactGroup& res )
{
    Resource::operator=( res );
    return *this;
}

QString Nepomuk2::ContactGroup::resourceTypeUri()
{
    return QLatin1String("http://www.semanticdesktop.org/ontologies/2007/03/22/nco#ContactGroup");
}

QStringList Nepomuk2::ContactGroup::contactGroupNames() const
{
    return ( property( QUrl::fromEncoded("http://www.semanticdesktop.org/ontologies/2007/03/22/nco#contactGroupName") ).toStringList());
}

void Nepomuk2::ContactGroup::setContactGroupNames( const QStringList& value )
{
    setProperty( QUrl::fromEncoded("http://www.semanticdesktop.org/ontologies/2007/03/22/nco#contactGroupName"), Variant( value ) );
}

void Nepomuk2::ContactGroup::addContactGroupName( const QString& value )
{
    Variant v = property( QUrl::fromEncoded("http://www.semanticdesktop.org/ontologies/2007/03/22/nco#contactGroupName") );
    v.append( value );
    setProperty( QUrl::fromEncoded("http://www.semanticdesktop.org/ontologies/2007/03/22/nco#contactGroupName"), v );
}

QString Nepomuk2::ContactGroup::contactGroupName() const
{
    return ( property( QUrl::fromEncoded("http://www.semanticdesktop.org/ontologies/2007/03/22/nco#contactGroupName") ).toStringList() << QString() ).first();
}

void Nepomuk2::ContactGroup::setContactGroupName( const QString& value )
{
    setProperty( QUrl::fromEncoded("http://www.semanticdesktop.org/ontologies/2007/03/22/nco#contactGroupName"), Variant( value ) );
}

QUrl Nepomuk2::ContactGroup::contactGroupNameUri()
{
    return QUrl::fromEncoded("http://www.semanticdesktop.org/ontologies/2007/03/22/nco#contactGroupName");
}


