/*
 * This file is part of the Nepomuk KDE project.
 *
 * This library is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation; either version 2 of the License, or
 * (at your option) any later version.
 * See the file "COPYING" for the exact licensing terms.
 */

/*
 * This file has been generated by the Nepomuk Resource class generator.
 * DO NOT EDIT THIS FILE.
 * ANY CHANGES WILL BE LOST.
 */

#include <nepomuk2/variant.h>
#include <nepomuk2/resourcemanager.h>
#include "organizationcontact.h"

#include "affiliation.h"

#include <QtCore/QDateTime>
#include <QtCore/QDate>
#include <QtCore/QTime>


Nepomuk2::OrganizationContact::OrganizationContact()
  : Contact( QUrl(), QUrl::fromEncoded("http://www.semanticdesktop.org/ontologies/2007/03/22/nco#OrganizationContact") )
{
}



Nepomuk2::OrganizationContact::OrganizationContact( const OrganizationContact& res )
  : Contact( res )
{
}


Nepomuk2::OrganizationContact::OrganizationContact( const Nepomuk2::Resource& res )
  : Contact( res )
{
}


Nepomuk2::OrganizationContact::OrganizationContact( const QString& uri )
  : Contact( uri, QUrl::fromEncoded("http://www.semanticdesktop.org/ontologies/2007/03/22/nco#OrganizationContact") )
{
}

Nepomuk2::OrganizationContact::OrganizationContact( const QUrl& uri )
  : Contact( uri, QUrl::fromEncoded("http://www.semanticdesktop.org/ontologies/2007/03/22/nco#OrganizationContact") )
{
}

Nepomuk2::OrganizationContact::OrganizationContact( const QString& uri, const QUrl& type )
  : Contact( uri, type )
{
}


Nepomuk2::OrganizationContact::OrganizationContact( const QUrl& uri, const QUrl& type )
  : Contact( uri, type )
{
}

Nepomuk2::OrganizationContact::~OrganizationContact()
{
}

Nepomuk2::OrganizationContact& Nepomuk2::OrganizationContact::operator=( const OrganizationContact& res )
{
    Resource::operator=( res );
    return *this;
}

QString Nepomuk2::OrganizationContact::resourceTypeUri()
{
    return QLatin1String("http://www.semanticdesktop.org/ontologies/2007/03/22/nco#OrganizationContact");
}

QList<Nepomuk2::Resource> Nepomuk2::OrganizationContact::logos() const
{
    // We always store all Resource types as plain Resource objects.
    // It does not introduce any overhead (due to the implicit sharing of
    // the data and has the advantage that we can mix setProperty calls
    // with the special Resource subclass methods.
    // More importantly Resource loads the data as Resource objects anyway.
    QList<Resource> rl;
    QList<Resource> l = property( QUrl::fromEncoded("http://www.semanticdesktop.org/ontologies/2007/03/22/nco#logo") ).toResourceList() ;
    for( QList<Resource>::const_iterator it = l.constBegin();
        it != l.constEnd(); ++it )
    rl.append( Resource( *it ) );
    return rl;
}

void Nepomuk2::OrganizationContact::setLogos( const QList<Nepomuk2::Resource>& value )
{
    setProperty( QUrl::fromEncoded("http://www.semanticdesktop.org/ontologies/2007/03/22/nco#logo"), Variant( value ) );
}

void Nepomuk2::OrganizationContact::addLogo( const Nepomuk2::Resource& value )
{
    // We always store all Resource types as plain Resource objects.
    // It does not introduce any overhead (due to the implicit sharing of
    // the data and has the advantage that we can mix setProperty calls
    // with the special Resource subclass methods.
    // More importantly Resource loads the data as Resource objects anyway.
    Variant v = property( QUrl::fromEncoded("http://www.semanticdesktop.org/ontologies/2007/03/22/nco#logo") );
    v.append( Resource( value ) );
    setProperty( QUrl::fromEncoded("http://www.semanticdesktop.org/ontologies/2007/03/22/nco#logo"), v );
}

QUrl Nepomuk2::OrganizationContact::logoUri()
{
    return QUrl::fromEncoded("http://www.semanticdesktop.org/ontologies/2007/03/22/nco#logo");
}


