/*
 * This file is part of the Nepomuk KDE project.
 *
 * This library is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation; either version 2 of the License, or
 * (at your option) any later version.
 * See the file "COPYING" for the exact licensing terms.
 */

/*
 * This file has been generated by the Nepomuk Resource class generator.
 * DO NOT EDIT THIS FILE.
 * ANY CHANGES WILL BE LOST.
 */

#include <nepomuk2/variant.h>
#include <nepomuk2/resourcemanager.h>
#include "parceldeliveryaddress.h"



#include <QtCore/QDateTime>
#include <QtCore/QDate>
#include <QtCore/QTime>


Nepomuk2::ParcelDeliveryAddress::ParcelDeliveryAddress()
  : PostalAddress( QUrl(), QUrl::fromEncoded("http://www.semanticdesktop.org/ontologies/2007/03/22/nco#ParcelDeliveryAddress") )
{
}



Nepomuk2::ParcelDeliveryAddress::ParcelDeliveryAddress( const ParcelDeliveryAddress& res )
  : PostalAddress( res )
{
}


Nepomuk2::ParcelDeliveryAddress::ParcelDeliveryAddress( const Nepomuk2::Resource& res )
  : PostalAddress( res )
{
}


Nepomuk2::ParcelDeliveryAddress::ParcelDeliveryAddress( const QString& uri )
  : PostalAddress( uri, QUrl::fromEncoded("http://www.semanticdesktop.org/ontologies/2007/03/22/nco#ParcelDeliveryAddress") )
{
}

Nepomuk2::ParcelDeliveryAddress::ParcelDeliveryAddress( const QUrl& uri )
  : PostalAddress( uri, QUrl::fromEncoded("http://www.semanticdesktop.org/ontologies/2007/03/22/nco#ParcelDeliveryAddress") )
{
}

Nepomuk2::ParcelDeliveryAddress::ParcelDeliveryAddress( const QString& uri, const QUrl& type )
  : PostalAddress( uri, type )
{
}


Nepomuk2::ParcelDeliveryAddress::ParcelDeliveryAddress( const QUrl& uri, const QUrl& type )
  : PostalAddress( uri, type )
{
}

Nepomuk2::ParcelDeliveryAddress::~ParcelDeliveryAddress()
{
}

Nepomuk2::ParcelDeliveryAddress& Nepomuk2::ParcelDeliveryAddress::operator=( const ParcelDeliveryAddress& res )
{
    Resource::operator=( res );
    return *this;
}

QString Nepomuk2::ParcelDeliveryAddress::resourceTypeUri()
{
    return QLatin1String("http://www.semanticdesktop.org/ontologies/2007/03/22/nco#ParcelDeliveryAddress");
}


